### ISSUE TITLE
question: what's the difference between this and kommentary?

### ISSUE THREAD

**Issue by alok** [gennaro-tedesco/nvim-commaround#10]
a short blurb would be nice

**Comment by gennaro-tedesco** [comment]
I suppose you are referring to [this one](https://github.com/b3nj5m1n/kommentary): if so, this plugin does not offer any additional features to kommentary, which in turn (if I understand the code correctly) also allows to use operator motions (mine does not), therefore in that respect kommentary is the more complete.

If I really ought to advocate for mine, I would say that the advantages are minimal to no configuration required (it works out of the box) and the direct exposure of the configuration for the user as `lua require('nvim-commaround.config').config[<newfiletype>] = {...}` (which seems to require few more lines of code in that case, judging from the README, but I may be wrong). This said, if you are using kommentary already there is no need to switch to anything else, and mine is not supposed to be a replacement of it (it was born as personal project and then I decided to offer it in case the community found it useful) :-)

**Comment by gennaro-tedesco** [comment]
Let me know if you have further questions, otherwise we can close this issue.

**Comment by chaitanyabsprip** [comment]
Does this work in normal mode?

**Comment by gennaro-tedesco** [comment]
No, it only works in visual selection mode. To be honest I have not really continued the development of this plugin too much: at the moment there are others that are superior and I would address you to them :)
