### ISSUE TITLE
Don't clear the content selected in the previous Visual Line mode 

### ISSUE THREAD

**Issue by kdurant** [gennaro-tedesco/nvim-commaround#12]
1.  select some lines in Visual Line mode 
2. use `<leader>c` to add comment
3. Comment can be toggled  by using `<leader>c` at anywhere in `normal` mode

**Comment by gennaro-tedesco** [comment]
Hi 👋🏼 ! Is this in the context of a bug report or feature request? I suspect the latter, if so would you provide a little more context?

From what I understand you would like the following behaviour:

- some comments are toggled somewhere in a buffer (via using standard visual selection)
- if later on `<leader>c` is invoked _without_ any visual selection (say in normal mode) then comments from the last visual selection are re-toggled (or un-toggled)

is my understanding correct?

**Comment by kdurant** [comment]
@gennaro-tedesco Yes, you are correct. I am sorry for my English.

**Comment by kdurant** [comment]
By the way, there is a bug in code below
```lua
vim.cmd('norm ^'..#filetype_config['single'] + 1 ..'x')
```

This will delete userful char like below
```lua
--print("hello world")
```

**Comment by gennaro-tedesco** [comment]
Regarding the idea of having `<leader>c` in normal mode defaulting to the last visual selection how would you see this work across buffers? Say you have different buffers with different filetypes and the following

1. buffer 1 - user makes a visual selection and toggles a comment
2. switch to buffer 2 - make another visual selection and toggle a comment
3. switch to buffer 3: `<leader>c` in normal mode: what would be triggered now?

Same goes when buffers/windows are opened/deleted.

(Moreover, what if instead the user toggles a visual selection and performs a different operation: would you default back to this visual selection or would you instead default back to the latest commented lines, independent of the visual selection?)

**Comment by gennaro-tedesco** [comment]
> By the way, there is a bug in code below
> 
> ```lua
> vim.cmd('norm ^'..#filetype_config['single'] + 1 ..'x')
> ```
> 
> This will delete userful char like below
> 
> ```lua
> --print("hello world")
> ```

About the above please open a separate issue replicating the expected behaviour (in contrast to the current one) and what file type it refers to.

**Comment by gennaro-tedesco** [comment]
Any update on the bug report as above (so that I can reproduce)?
